name = "Tragically Falling"
author = "SwimMau5"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a01d36b7addfc1295cf832d57caf852d4a28cd07f4d5c64cc93a9dd81036aa4"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
