name = "Tragically Falling"
author = "SwimMau5"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7b8156c513c27686b562ca0f062ec02b8145f02929c4c89be4a796abafe335"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
